import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-blop-background bg-no-repeat bg-bottom bg- min-h-screen bg-[length:35rem_35rem]`}
      >
        <div className="mx-3 mt-3">{children}</div>
      </body>
    </html>
  );
}
